---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gke-test-blue"
  namespace: "default"
  labels:
    app: "gke-test-blue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gke-test-blue"
  template:
    metadata:
      labels:
        app: "gke-test-blue"
    spec:
      containers:
      - name: "gke-test-blue"
        image: "gcr.io/gke-test-324522/gke-test"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "gke-test-blue-autoscaler"
  namespace: "default"
  labels:
    app: "gke-test-blue"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "gke-test-blue"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gke-test-blue-service"
  namespace: "default"
  labels:
    app: "gke-test-blue"
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 20000
  selector:
    app: "gke-test-blue"
  type: "ClusterIP"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gke-test-green"
  namespace: "default"
  labels:
    app: "gke-test-green"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gke-test-green"
  template:
    metadata:
      labels:
        app: "gke-test-green"
    spec:
      containers:
      - name: "gke-test-green"
        image: "gcr.io/gke-test-324522/gke-test"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "gke-test-green-autoscaler"
  namespace: "default"
  labels:
    app: "gke-test-green"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "gke-test-green"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gke-test-green-service"
  namespace: "default"
  labels:
    app: "gke-test-green"
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 20000
  selector:
    app: "gke-test-green"
  type: "ClusterIP"
