---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gke-test-blue"
  namespace: "default"
  labels:
    app: "gke-test-blue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gke-test-blue"
  template:
    metadata:
      labels:
        app: "gke-test-blue"
    spec:
      containers:
      - name: "gke-test-blue"
        image: "gcr.io/gke-test-324522/gke-test"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa-vxzd"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
